# Generated by Django 3.2.7 on 2021-09-18 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('h', 'مخفی'), ('s', 'نمایش در سایت')], default='h', max_length=1)),
            ],
            options={
                'verbose_name': 'نوشته کوتاه ',
                'verbose_name_plural': 'نوشته های کوتاه',
            },
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 13, 58, 49, 466877, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='thumnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=posts.models.PostModel.image_path, verbose_name='تصویر'),
        ),
    ]
