# Generated by Django 3.2.7 on 2021-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع دنبال کردن')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirm_code', models.CharField(max_length=15, verbose_name='کد تایید')),
                ('recived_post', models.ManyToManyField(related_name='subscribed', to='posts.PostModel', verbose_name='پست های دریافتی')),
            ],
            options={
                'verbose_name': 'دنبال کننده',
                'verbose_name_plural': 'دنبال کنندگان ',
            },
        ),
    ]
